### ISSUE TITLE
Error with N/A ranked shows.

### ISSUE THREAD

**Issue by SnipersLaww** [JohnDoee/web-parsers#3]
Error I am getting when a user does a search for an R18+ show (all of these rated shows are unranked)

ValueError: invalid literal for int() with base 10: 'N/A' (file "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/malparser/base.py", line 64, in <lambda>)

This is the corresponding line:

```
    strip2int = lambda x:int(x.strip('#'))
```

**Comment by JohnDoee** [comment]
Should be fixed now, thanks for reporting it. 

Having fetched over 2000 pages myself, I've apparently never fetched hentai :)
